export const images = [
  {
    id: 1,
    src: "/river_through_time.png",
    width: 270,
    height: 250,
    alt: "Editorial design exploring rivers, archives, and human relationships to water",
    path: "rivers",
    title: "",
    year: 2025,
    description: `Rivers Through Time & Vision, editorial design.
Archival journey based off our relationship to rivers.`,
    gridColumn: "3",
    gridRow: "1",
    hash: "river",
  },
  {
    id: 2,
    src: "/rivers.gif",
    width: 288,
    height: 250,
    alt: "Editorial design exploring rivers, archives, and human relationships to water",
    path: "rivers",
    title: "",
    year: 2025,
    description: "",
    gridColumn: "4",
    gridRow: "1",
  },
  {
    id: 3,
    src: "/3d-letter-r.png",
    width: 310,
    height: 250,
    alt: "Experimental 3D typographic forms created in Cinema 4D",
    path: "3d",
    title: "",
    year: 2025,
    description: "Typographical 3D experimentation on c4d",
    gridColumn: "2",
    gridRow: "2",
    hash: "r3d",
  },
  {
    id: 4,
    src: "/rosa-mota-robles-card.png",
    width: 320,
    height: 375,
    alt: "Minimal business card design for Rosa Mota Robles",
    path: "Rosa business card",
    title: "",
    year: 2025,
    description: "",
    gridColumn: "1",
    gridRow: "2",
    hash: "business-card",
  },
  {
    id: 5,
    src: "/mouth-guard.gif",
    width: 690,
    height: 490,
    alt: "Animated cover of The Mouth Guard fanzine about dental language and appliances",
    path: "mouth-guard",
    title: "",
    description: `, a fanzine about mouth appliances and other dental related words. 
All copiesbound sewn with dental floss.`,
    year: 2025,
    gridColumn: "3",
    gridRow: "2",
    hash: "mouth-guard",
    italicTitle: "THE MOUTH GUARD",
  },

  {
    id: 6,
    src: "/stencil.gif",
    width: 330,
    height: 500,
    alt: "Stencil versus print experiment from Elisava Graphic Lab",
    path: "stencil",
    title: "",
    description: "Stencil vs. Print experiment @ Elisava's Graphic Lab",
    year: 2025,
    gridColumn: "2",
    gridRow: "3",
    hash: "stencil-fauno",
  },
  {
    id: 7,
    src: "/clickgard.webp",
    width: 690,
    height: 395,
    alt: "Visual identity and art direction for Click.Garden sustainability platform",
    path: "click-garden",
    title: "",
    description: `Click.Garden’s aim is to cultivate awareness and disseminate knowledge at the intersection of creativity, technology and sustainability. Focusing in the importance of highlighting other ways of creating, 
taking into account the consequences that technology has on our planet.Art Direction and design along with Lea Naisberg and Lucrecia Strano. 
`,
    year: 2025,
    gridColumn: "3",
    gridRow: "4",
    hash: "click-garden",
  },
  {
    id: 8,
    src: "/main-derrota.png",
    width: 690,
    height: 480,
    alt: "Still from La Derrota, an experimental short film about identity and disappearance",
    path: "la-derrota",
    title: "",
    description: ` is a self written, directed, produced, recorded, and edited short film. 
It speaks of the fear to disappear, to stolen identities, and to oneself.`,
    year: 2023,
    gridColumn: "1",
    gridRow: "5",
    hash: "la-derrota",
    italicTitle: "LA DERROTA",
  },
  {
    id: 9,
    src: "/clickg2.webp",
    width: 320,
    height: 250,
    alt: `Detail from Click.Garden visual identity project`,
    path: "click-garden",
    title: "",
    description: ``,
    year: 2025,
    gridColumn: "3",
    gridRow: "6",
    hash: "click-garden-sm",
  },
  {
    id: 10,
    src: "/clickg1.webp",
    width: 320,
    height: 250,
    alt: "Secondary layout from Click.Garden design system",
    path: "click-garden",
    title: "",
    description: ``,
    year: 2025,
    gridColumn: "4",
    gridRow: "6",
    hash: "click-garden-bg",
  },
  {
    id: 11,
    src: "/m-marmari.gif",
    width: 690,
    height: 1020,
    alt: "Animated specimen of Marmari, a modular typeface based on geometric grids",
    path: "Marmari",
    title: "",
    description: ` is a modular typeface based off a square + circle grid.  Following a strict and repetitive pattern, it becomes a series of characters whose curves evoke movement and playfulness. 

Here, riso copies with pink + yellow + teal +blue ink.
`,
    year: 2025,
    gridColumn: "2",
    gridRow: "8",
    hash: "marmari-font",
    italicTitle: "Marmari",
  },
  {
    id: 12,
    src: "/self.png",
    width: 320,
    height: 410,
    alt: "Digital self-portrait illustration",
    path: "Digital Illustration",
    title: "",
    description: ", 2022. Digital illustration.",
    year: 2025,
    gridColumn: "1",
    gridRow: "9",
    hash: "self-portrait",
    italicTitle: "Self portrait",
  },
  {
    id: 13,
    src: "/n-marmari.gif",
    width: 320,
    height: 380,
    alt: "Marmari addition",
    path: "Marmari",
    title: "",
    description: "",
    year: 2025,
    gridColumn: "4",
    gridRow: "10",
  },
  {
    id: 14,
    src: "/bufanda.png",
    width: 320,
    height: 1675,
    alt: "Ornamental scarf",
    path: "ornament",
    title: "",
    description: "Ornamental Scarf",
    year: 2025,
    gridColumn: "1",
    gridRow: "12",
    hash: "ornament-scarf",
  },
  {
    id: 15,
    src: "/no-olvides-libro.jpg",
    width: 320,
    height: 204,
    alt: "Cover of Cinque Histoires, a short stories fanzine designed in Paris",
    path: "5histories",
    title: "",
    description:
      "Book conception, editorial and graphic design for this short stories fanzine gathers writings from my first 5 months in Paris, titled cinq histoires.",
    year: 2022,
    gridColumn: "2",
    gridRow: "14",
    hash: "5-histories",
  },
  {
    id: 16,
    src: "/5histoires.gif",
    width: 300,
    height: 200,
    alt: "Cover of Cinque Histoires, a short stories fanzine designed in Paris",
    path: "5histories",
    title: "",
    description: "",
    year: 2022,
    gridColumn: "2",
    gridRow: "15",
  },
  {
    id: 17,
    src: "/tarot-main.png",
    width: 690,
    height: 780,
    alt: "Illustrated card Le Tarot de Paris",
    path: "tarot",
    title: "",
    description:
      "Le Tarot de Paris is a set of illustrated cards that reinterprets the classic version.",
    year: 2024,
    gridColumn: "3",
    gridRow: "16",
    hash: "tarot-paris",
  },
  {
    id: 18,
    src: "/bernardina.gif",
    width: 744,
    height: 537,
    alt: "bernandina font",
    path: "bernandina",
    title: "",
    year: 2025,
    description: ` is a typography designed to follow the sharpness of an inked nib.
Carefully crafted, stencil-proofed, free use.`,
    hash: "bernandina",
    italicTitle: "Bernardina",
  },
  {
    id: 19,
    src: "/bernastencil.gif",
    width: 320,
    height: 500,
    alt: "Animated specimen of Bernardina, a stencil-proof typeface inspired by inked nibs",
    path: "bernandina",
    title: "",
    year: 2025,
    description: `Bernardina in use for the Graphic Lab’s stencil manual.`,
    hash: "bernandina-stencil",
  },
  {
    id: 20,
    src: "/aestehtics_low.gif",
    width: 320,
    height: 541,
    alt: "Aesthetics of the ugly ",
    path: "aestheticsoftheugly",
    title: "",
    year: 2025,
    description: ` is an essay that unravels the meaning of the bad, the tacky, and beyond`,
    hash: "aesthetics-of-the-ugly",
    italicTitle: "The aesthetics of the ugly",
  },
  {
    id: 21,
    src: "/aestheticsoftheugly.gif",
    width: 320,
    height: 230,
    alt: "Aesthetics of the ugly",
    path: "aestheticsoftheugly",
    title: "",
    year: 2025,
    description: ``,
  },
  {
    id: 22,
    src: "/no-olvides-in.jpg",
    width: 322,
    height: 250,
    title: "",
    alt: "Book cover for No olvides, a project about memory and grandmothers’ stories",
    path: "no-olvides",
    year: 2020,
    description: ` (do not forget) is a project that speaks about the memories and experiences of 6 grandmothers. Book design, photography and illustration by myself, their own words, and nothing more than a small tribute to all of them. Limited edition of 100 copies.`,
    gridColumn: "1",
    gridRow: "7",
    hash: "no-olvides",
    italicTitle: "No olvides",
  },
  {
    id: 23,
    src: "/t-3d.png",
    width: 690,
    height: 553,
    alt: "3D typography",
    path: "3d",
    title: "",
    year: 2025,
    description: "Typographical 3D experimentation on c4d",
    hash: "t3d",
  },
];

export type HoveredImage = {
  id: number;
  src: string;
  width: number;
  height: number;
  alt: string;
  path?: string;
  title?: string;
  description: string;
  year: number;
};
