export const images = [
  {
    id: 1,
    src: "/river.png",
    width: 270,
    height: 250,
    alt: "Rivers Through Time & Vision",
    path: "rivers",
    title: "",
    year: 2025,
    description: `Rivers Through Time & Vision, editorial design.
Archival journey based off our relationship to rivers.`,
    gridColumn: "3",
    gridRow: "1",
    hash: "river",
  },
  {
    id: 2,
    src: "",
    width: 288,
    height: 250,
    alt: "Rivers Through Time & Vision",
    path: "rivers",
    title: "",
    year: 2025,
    description: "",
    gridColumn: "4",
    gridRow: "1",
  },
  {
    id: 3,
    src: "/r.png",
    width: 310,
    height: 250,
    alt: "3D typography",
    path: "3d",
    title: "",
    year: 2025,
    description: "Typographical 3D experimentation on c4d",
    gridColumn: "2",
    gridRow: "2",
    hash: "r3d",
  },
  {
    id: 4,
    src: "/card.png",
    width: 320,
    height: 350,
    alt: "Rosa business card",
    path: "Rosa business card",
    title: "",
    year: 2025,
    description: "",
    gridColumn: "1",
    gridRow: "2",
    hash: "business-card",
  },
  {
    id: 5,
    src: "/mouth-guard.gif",
    width: 690,
    height: 490,
    alt: "The mouth guard",
    path: "mouth-guard",
    title: "",
    description: `The Mouth Guard, a fanzine about mouth appliances and other dental related words. 
All copiesbound sewn with dental floss.`,
    year: 2025,
    gridColumn: "3",
    gridRow: "2",
    hash: "mouth-guard",
  },

  {
    id: 6,
    src: "/stencil_fauno.gif",
    width: 330,
    height: 480,
    alt: "Stencil gif",
    path: "stencil",
    title: "",
    description: "Stencil vs. Print experiment @ Elisava's Graphic Lab",
    year: 2025,
    gridColumn: "2",
    gridRow: "3",
    hash: "stencil-fauno",
  },
  {
    id: 7,
    src: "/clickgard.webp",
    width: 690,
    height: 395,
    alt: "Click garden",
    path: "click-garden",
    title: "",
    description: `Click.Garden’s aim is to cultivate awareness and disseminate knowledge at the intersection of creativity, technology and sustainability. Focusing in the importance of highlighting other ways of creating, 
taking into account the consequences that technology has on our planet. Art Direction and design along with Lea Naisberg and Lucrecia Strano. 
`,
    year: 2025,
    gridColumn: "3",
    gridRow: "4",
    hash: "click-garden",
  },
  {
    id: 8,
    src: "/main-derrota.png",
    width: 690,
    height: 480,
    alt: "la derrota",
    path: "la-derrota",
    title: "",
    description: `LA DERROTA is a self written, directed, produced, recorded, and edited short film. 
It speaks of the fear to disappear, to stolen identities, and to oneself.`,
    year: 2023,
    gridColumn: "1",
    gridRow: "5",
    hash: "la-derrota",
  },
  {
    id: 9,
    src: "/clickg2.webp",
    width: 320,
    height: 250,
    alt: "click garden part",
    path: "click-garden",
    title: "",
    description: ``,
    year: 2025,
    gridColumn: "3",
    gridRow: "6",
    hash: "click-garden-sm",
  },
  {
    id: 10,
    src: "/clickg1.webp",
    width: 320,
    height: 250,
    alt: "click garden part right",
    path: "click-garden",
    title: "",
    description: ``,
    year: 2025,
    gridColumn: "4",
    gridRow: "6",
    hash: "click-garden-bg",
  },
  {
    id: 11,
    src: "/m-marmari.gif",
    width: 690,
    height: 1020,
    alt: "Marmari font",
    path: "Marmari",
    title: "",
    description: `Marmari is a modular typeface based off a square + circle grid.  Following a strict and repetitive pattern, it becomes a series of characters whose curves evoke movement and playfulness. 

Here, riso copies with pink + yellow + teal +blue ink.
`,
    year: 2025,
    gridColumn: "2",
    gridRow: "8",
    hash: "marmari-font",
  },
  {
    id: 12,
    src: "/self.png",
    width: 320,
    height: 410,
    alt: "Self portrait digital illustration",
    path: "Digital Illustration",
    title: "",
    description: "Self portrait, 2022. Digital illustration.",
    year: 2025,
    gridColumn: "1",
    gridRow: "9",
    hash: "self-portrait",
  },
  {
    id: 13,
    src: "/n-marmari.gif",
    width: 320,
    height: 380,
    alt: "Marmari addition",
    path: "Marmari",
    title: "",
    description: "",
    year: 2025,
    gridColumn: "4",
    gridRow: "10",
  },
  {
    id: 14,
    src: "/bufanda.png",
    width: 320,
    height: 1675,
    alt: "Marmari addition",
    path: "Marmari",
    title: "",
    description: "Ornamental Scarf",
    year: 2025,
    gridColumn: "1",
    gridRow: "12",
    hash: "marmari-scarf",
  },
  {
    id: 15,
    src: "/main.jpg",
    width: 320,
    height: 204,
    alt: "5 histories",
    path: "5histories",
    title: "",
    description:
      "Book conception, editorial and graphic design for this short stories fanzine gathers writings from my first 5 months in Paris, titled cinq histoires.",
    year: 2022,
    gridColumn: "2",
    gridRow: "14",
    hash: "5-histories",
  },
  {
    id: 16,
    src: "/5histoires.gif",
    width: 300,
    height: 200,
    alt: "5 histories",
    path: "5histories",
    title: "",
    description: "",
    year: 2022,
    gridColumn: "2",
    gridRow: "15",
  },
  {
    id: 17,
    src: "/tarot-main.png",
    width: 690,
    height: 780,
    alt: "tarot-project",
    path: "tarot",
    title: "",
    description:
      "Le Tarot de Paris is a set of illustrated cards that reinterprets the classic version.",
    year: 2024,
    gridColumn: "3",
    gridRow: "16",
    hash: "tarot-paris",
  },
  {
    id: 18,
    src: "/bernardina.gif",
    width: 744,
    height: 537,
    alt: "bernandina font",
    path: "bernandina",
    title: "",
    year: 2025,
    description: `Bernardina is a typography designed to follow the sharpness of an inked nib.
Carefully crafted, stencil-proofed, free use.`,
    hash: "bernandina",
  },
  {
    id: 19,
    src: "/bernastencil.gif",
    width: 320,
    height: 500,
    alt: "bernandina font",
    path: "bernandina",
    title: "",
    year: 2025,
    description: `Bernardina in use for the Graphic Lab’s stencil manual.`,
    hash: "bernandina-stencil",
  },
  {
    id: 20,
    src: "/aestehtics_low.gif",
    width: 320,
    height: 541,
    alt: "Aesthetics of the ugly ",
    path: "aestheticsoftheugly",
    title: "",
    year: 2025,
    description: `the aesthetics of the ugly is an essay that unravels the meaning of the bad, the tacky, and beyond`,
    hash: "aesthetics-of-the-ugly",
  },
  {
    id: 21,
    src: "/aestheticsoftheugly.gif",
    width: 320,
    height: 230,
    alt: "Aesthetics of the ugly",
    path: "aestheticsoftheugly",
    title: "",
    year: 2025,
    description: ``,
  },
  {
    id: 22,
    src: "/no-olvides-in.jpg",
    width: 322,
    height: 250,
    title: "",
    alt: "main-olvides",
    path: "no-olvides",
    year: 2020,
    description: `<No olvides>" (do not forget) is a project that speaks about the memories and experiences of 6 grandmothers. Book design, photography and illustration by myself, their own words, and nothing more than a small tribute to all of them. Limited edition of 100 copies.`,
    gridColumn: "1",
    gridRow: "7",
    hash: "no-olvides",
  },
  {
    id: 23,
    src: "/t-3d.png",
    width: 690,
    height: 553,
    alt: "3D typography",
    path: "3d",
    title: "",
    year: 2025,
    description: "Typographical 3D experimentation on c4d",
    hash: "t3d",
  },
];

export type HoveredImage = {
  id: number;
  src: string;
  width: number;
  height: number;
  alt: string;
  path?: string;
  title?: string;
  description: string;
  year: number;
};
